version: '3'

networks:
  default:
    external:
      name: wwb

services:

  wwb-stream:
    build: .
    ports:
     - "3002:3002"
     - "3003:3003"
     - "3004:3004"
    environment:
     - HEALTH_PORT=3002
     - TEXT_PORT=3003
     - DRAW_PORT=3004
     - DRAW_LOGGING=true
     - REDIS_URL=redis://redis:6379
     - MONGO_URL=mongodb://mongo:27017/wwb




