version: '3'
services:

  mongo:
    image: "mongo"
    ports:
     - "27017:27017"

  redis:
    image: "redis"
    ports:
     - "6379:6379"

  wwb-stream:
    build: .
    ports:
     - "3002:3002"
     - "3003:3003"
     - "3004:3004"
    depends_on:
     - mongo
     - redis
    environment:
     - HEALTH_PORT=3002
     - TEXT_PORT=3003
     - DRAW_PORT=3004
     - REDIS_URL=redis://redis:6379
     - MONGO_URL=mongodb://mongo:27017/wwb




